"""Pydantic schemas for personalized recommendations."""

from pydantic import BaseModel, Field

from app.schemas.library import LibraryBook


class Recommendation(BaseModel):
    """One suggested book, with the reason it was suggested.

    The book is a `LibraryBook` — the same shape the history renders — so
    the client draws one card type, and so "Want to read" on a
    recommendation is the ordinary `PUT /books/{id}/library` rather than a
    second write path. That works because a recommended book is a real,
    persisted `Book` row by the time it reaches here.
    """

    book: LibraryBook
    #: Cosine similarity to the reader's profile vector, `0`-`1`.
    score: float = Field(ge=0.0, le=1.0)
    #: Why this book is here, e.g. "Because you liked Dune". **Computed,
    #: never generated by a model.** It is derived from the nearest book in
    #: the reader's own library, so it states a fact about their history
    #: rather than a plausible sentence about it — and a wrong explanation
    #: next to a right recommendation is worse than no explanation at all.
    explanation: str
    #: The library book the explanation names, so the client can link to
    #: it. `None` should not happen for a returned recommendation, but the
    #: field is optional rather than the explanation being asserted.
    because_of_book_id: int | None = None


class RecommendationList(BaseModel):
    """The recommendations for one reader, plus what they were built from.

    `based_on` is what lets the client tell two empty results apart, and
    they need completely different screens:

    - `based_on == 0` — nothing has been rated 4+ yet, or the liked books
      are catalogued too thinly to characterise. There is no profile to
      recommend against, and the honest answer is to ask for a rating.
    - `based_on > 0` with an empty list — the profile exists and the
      catalogs simply had nothing new to offer past the reader's own
      library. That is "check back later", not "rate something".

    Collapsing the two into a bare empty array would make the app ask a
    reader who has rated forty books to please rate a book.
    """

    recommendations: list[Recommendation] = []
    #: How many of the reader's liked books actually fed the profile
    #: vector. Deliberately **not** the same number as
    #: `LibraryPreferences.based_on`, which counts everything rated 4+: a
    #: liked book the catalogs describe with nothing but its own title has
    #: no profile vector and cannot contribute here.
    based_on: int = 0
